// Linear Actuator Pins
#define STEPPIN 8
#define DIRPIN 9
#define ENAPIN 10

// Linear Motion Pins
#define CATHETER_LINEAR_POSITIVE_PIN 39
#define CATHETER_LINEAR_GROUND_PIN 38
#define CATHETER_LINEAR_ENCODER_A_PIN 48
#define CATHETER_LINEAR_ENCODER_B_PIN 49
#define CATHERER_LINEAR_PWM_PIN 3
#define CATHETER_LINEAR_DIR_A_PIN 27
#define CATHETER_LINEAR_DIR_B_PIN 26

// Bending Motion Pins
#define CATHETER_BENDING_POSITIVE_PIN 37
#define CATHETER_BENDING_GROUND_PIN 36
#define CATHETER_BENDING_ENCODER_A_PIN 46
#define CATHETER_BENDING_ENCODER_B_PIN 47
#define CATHERER_BENDING_PWM_PIN 4
#define CATHETER_BENDING_DIR_A_PIN 25
#define CATHETER_BENDING_DIR_B_PIN 24

// Rotation Pins
#define CATHETER_ROTATION_POSITIVE_PIN 35
#define CATHETER_ROTATION_GROUND_PIN 34
#define CATHETER_ROTATION_ENCODER_A_PIN 44
#define CATHETER_ROTATION_ENCODER_B_PIN 45
#define CATHERER_ROTATION_PWM_PIN 5
#define CATHETER_ROTATION_DIR_A_PIN 23
#define CATHETER_ROTATION_DIR_B_PIN 22
