// Linear Actuator Pins
#define STEPPIN 8
#define DIRPIN 9
#define ENAPIN 10

// CATHETER ASSEMBLY

  // Bending Motion Pins
    //#define CATHETER_BENDING_POSITIVE_PIN 37
    //#define CATHETER_BENDING_GROUND_PIN 36
    #define CATHETER_BENDING_ENCODER_A_PIN 40
    #define CATHETER_BENDING_ENCODER_B_PIN 41
    #define CATHETER_BENDING_PWM_PIN 4
    #define CATHETER_BENDING_DIR_A_PIN 26
    #define CATHETER_BENDING_DIR_B_PIN 27
  //


  // Rotating Motion Pins
    #define CATHETER_ROTATION_ENCODER_A_PIN 38
    #define CATHETER_ROTATION_ENCODER_B_PIN 39
    #define CATHETER_ROTATION_PWM_PIN 5
    #define CATHETER_ROTATION_DIR_A_PIN 24
    #define CATHETER_ROTATION_DIR_B_PIN 25
    
// 


// ASSIST ASSEMBLY
  // Linear Motion Pins
    //#define ASSIST_LINEAR_POSITIVE_PIN 39
    //#define ASSIST_LINEAR_GROUND_PIN 38
    #define ASSIST_LINEAR_ENCODER_A_PIN 44
    #define ASSIST_LINEAR_ENCODER_B_PIN 45
    #define ASSIST_LINEAR_PWM_PIN 2
    #define ASSIST_LINEAR_DIR_A_PIN 30
    #define ASSIST_LINEAR_DIR_B_PIN 31
  //

  // Rotation Pins
    //#define ASSIST_ROTATION_POSITIVE_PIN 35
    //#define ASSIST_ROTATION_GROUND_PIN 34
    #define ASSIST_ROTATION_ENCODER_A_PIN 42
    #define ASSIST_ROTATION_ENCODER_B_PIN 43
    #define ASSIST_ROTATION_PWM_PIN 3
    #define ASSIST_ROTATION_DIR_A_PIN 29
    #define ASSIST_ROTATION_DIR_B_PIN 28
  //
//

